
language: node_js
node_js:
  - "node"

install:
  - npm install

script:
  - npm run lint
  - npm run test

before_deploy:
  - npm run build:clean
  - npm run build:docs

deploy:
  github_token: $TRAVIS_GITHUB_TOKEN
  keep_history: true
  local_dir: docs
  on:
    branch: master
  provider: pages
  skip_cleanup: true
  target_branch: gh-pages
