name: Publish to GH Pages

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install
        run: npm install
      - name: Build
        run: npm run build:clean && npm run build:docs
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
